# Generated by Django 5.1.6 on 2025-03-26 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='page_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
